language: python

python:
- 2.7

before_script:
- pip install -r requirements.txt
- pip install -r requirements-test.txt

script:
- make test
- make bandit
- make emulambda

after_success:
- coveralls
- coverage xml
- python-codacy-coverage -r coverage.xml

deploy:
- provider: pypi
  distributions: sdist
  server: https://test.pypi.org/legacy/
  user: iamjohnnym
  password:
    secure: t67YMVegc6Ndnm0GbmWlHLK8/Prj8zDcPvPyECW5hPIL6q+LYHLP8DwpU84lBKWtiWw1kZgNAS/7NTz7C0AolgF9n/a+7QWqEyvWVllRkrKPcvjbc3SmrGJO311nvmCC4VIQoTJG96tVen83suaXPXMnbLXKShwJtkD8Sq6Yg4pMFXnfu2fG3gtKHTuTyHiDR914/vsgZMPQQARMTMPjPYU3VtAKpPaAcFHe+NwB0YdsqZlHLMokoCwrQF239VkL0YOxSyDtLRRFbJbL+nmOIRaaYLJ+JJssKtbuYGU5AOCMmuMSLqBtp9uZwdCpEWDz0X+62B1haOa+CrtUL+O+sBnXgmVtDo6vRU9Tmucyn3SNahL9d2I3uqZYL8at6EFUQ5qLLJCbeCFOhwyU4QfaCQFx7EtfK1jxM5T8YHSIyKziJxsVzB7UHiiBMNpGjbnjvuyP4gkDqmexh/Ky/nIueDx+ry2S0QHTZbqaVcZjyvRAPKTIAU4Jwxm+TXZd2b2vHrzPcJtCCIIAHxJL0uOjtm0975rDbwt1EAP57ew1cYm6tURVoTIkn7/O/JpuWvLfCgeRklWFAZGYg4QCdQx8/0yXnYlDLQQZW0MWTMXgM1S1sr1Uy6Vwntgm4hCAtFuUd8CyJxjDjr76TNJf2n14bYgfyXYR7HZGPi4aqS9LOd8=
  on:
    branch: staging
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
- provider: pypi
  distributions: sdist
  server: https://test.pypi.org/legacy/
  user: iamjohnnym
  password:
    secure: t67YMVegc6Ndnm0GbmWlHLK8/Prj8zDcPvPyECW5hPIL6q+LYHLP8DwpU84lBKWtiWw1kZgNAS/7NTz7C0AolgF9n/a+7QWqEyvWVllRkrKPcvjbc3SmrGJO311nvmCC4VIQoTJG96tVen83suaXPXMnbLXKShwJtkD8Sq6Yg4pMFXnfu2fG3gtKHTuTyHiDR914/vsgZMPQQARMTMPjPYU3VtAKpPaAcFHe+NwB0YdsqZlHLMokoCwrQF239VkL0YOxSyDtLRRFbJbL+nmOIRaaYLJ+JJssKtbuYGU5AOCMmuMSLqBtp9uZwdCpEWDz0X+62B1haOa+CrtUL+O+sBnXgmVtDo6vRU9Tmucyn3SNahL9d2I3uqZYL8at6EFUQ5qLLJCbeCFOhwyU4QfaCQFx7EtfK1jxM5T8YHSIyKziJxsVzB7UHiiBMNpGjbnjvuyP4gkDqmexh/Ky/nIueDx+ry2S0QHTZbqaVcZjyvRAPKTIAU4Jwxm+TXZd2b2vHrzPcJtCCIIAHxJL0uOjtm0975rDbwt1EAP57ew1cYm6tURVoTIkn7/O/JpuWvLfCgeRklWFAZGYg4QCdQx8/0yXnYlDLQQZW0MWTMXgM1S1sr1Uy6Vwntgm4hCAtFuUd8CyJxjDjr76TNJf2n14bYgfyXYR7HZGPi4aqS9LOd8=
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
- provider: pypi
  distributions: sdist
  user: iamjohnnym
  password:
    secure: t67YMVegc6Ndnm0GbmWlHLK8/Prj8zDcPvPyECW5hPIL6q+LYHLP8DwpU84lBKWtiWw1kZgNAS/7NTz7C0AolgF9n/a+7QWqEyvWVllRkrKPcvjbc3SmrGJO311nvmCC4VIQoTJG96tVen83suaXPXMnbLXKShwJtkD8Sq6Yg4pMFXnfu2fG3gtKHTuTyHiDR914/vsgZMPQQARMTMPjPYU3VtAKpPaAcFHe+NwB0YdsqZlHLMokoCwrQF239VkL0YOxSyDtLRRFbJbL+nmOIRaaYLJ+JJssKtbuYGU5AOCMmuMSLqBtp9uZwdCpEWDz0X+62B1haOa+CrtUL+O+sBnXgmVtDo6vRU9Tmucyn3SNahL9d2I3uqZYL8at6EFUQ5qLLJCbeCFOhwyU4QfaCQFx7EtfK1jxM5T8YHSIyKziJxsVzB7UHiiBMNpGjbnjvuyP4gkDqmexh/Ky/nIueDx+ry2S0QHTZbqaVcZjyvRAPKTIAU4Jwxm+TXZd2b2vHrzPcJtCCIIAHxJL0uOjtm0975rDbwt1EAP57ew1cYm6tURVoTIkn7/O/JpuWvLfCgeRklWFAZGYg4QCdQx8/0yXnYlDLQQZW0MWTMXgM1S1sr1Uy6Vwntgm4hCAtFuUd8CyJxjDjr76TNJf2n14bYgfyXYR7HZGPi4aqS9LOd8=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
